export default {
    index: 'Developer portal',
    '0###': { type: 'separator', title: 'General' },
    market_platforms: 'Market platforms',
    information_exchange: 'Information exchange',
    cim: 'Common Information Model - CIM',
    about: 'About',
    '1###': { type: 'separator', title: 'Market Platforms' },
    mFRR_C: 'Balancing capacity markets (mFRR)',
    mFRR_E: 'Balancing energy markets (mFRR)',
    aFRR_C: 'Automatic frequency restoration reserve capacity markets (aFRR)',
    aFRR_E: 'Automatic frequency restoration reserve energy markets (aFRR)',
    FCR: 'Frequency containment reserves (FCR products)', 
    FFR: 'Fast Frequency Reserve (FFR)',
  }
