name: publish-to-github-pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: enable corepack and set pnpm version
        run: |
          corepack enable
          corepack prepare pnpm@latest-10 --activate
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Setup pnpm
        run: |
          pnpm config set @fingrid.registry "https://pkgs.dev.azure.com/fingrid/Ohjelmistokehitys/_packaging/fingrid-npm/npm/registry/"
          pnpm config set//pkgs.dev.azure.com/fingrid/Ohjelmistokehitys/_packaging/fingrid-npm/npm/registry/:_authToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.ADO_PAT }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
        #with: // Still fails - this time due to type error
        #  static_site_generator: next
      - name: Build
        run: |
          pnpm i --frozen-lockfile
          pnpm build
          touch ./out/.nojekyll # Prevent Jekyll from processing the site
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
