name: publish-to-github-pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: enable corepack and set yarn version to latest stable
        run: |
          corepack enable
          yarn set version stable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Setup .yarnrc.yml
        run: |
            yarn config set npmScopes.fingrid.npmRegistryServer "https://pkgs.dev.azure.com/fingrid/Ohjelmistokehitys/_packaging/fingrid-npm/npm/registry/"
            yarn config set npmScopes.fingrid.npmAlwaysAuth true
            yarn config set npmScopes.fingrid.npmAuthToken $NPM_AUTH_TOKEN
        env:
            NPM_AUTH_TOKEN: ${{ secrets.ADO_PAT }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
        #with: // Still fails - this time due to type error
        #  static_site_generator: next
      - name: Build
        run: |
          yarn install --immutable
          yarn build
          touch ./out/.nojekyll # Prevent Jekyll from processing the site
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
